FROM mysql

ENV MYSQL_ROOT_PASSWORD=f6g8En2J \
    MYSQL_USER=wait_time_management \
    MYSQL_PASSWORD=Wru48vWy \
    MYSQL_DATABASE=wait_time_management

ADD ./wait_time_management.sql /docker-entrypoint-initdb.d/
